---
name: selene
description: A blazing-fast modern Lua linter written in Rust.
homepage: https://kampfkarren.github.io/selene/
licenses:
  - MPL-2.0
languages:
  - Lua
  - Luau
categories:
  - Linter

source:
  id: pkg:github/jsenjobs/selene-fix-aarch64@0.27.2
  # fix aarch64
  # id: pkg:github/Kampfkarren/selene@0.27.1
  asset:
    - target: [darwin_arm64, darwin_x64]
      file: selene-{{version}}-macos.zip
      bin: selene
    - target: linux_x64
      file: selene-{{version}}-linux.zip
      bin: selene
    - target: linux_arm64_gnu
      file: selene-{{version}}-linux-aarch64.zip
      bin: lemminx-linux
    - target: win_x64
      file: selene-{{version}}-windows.zip
      bin: selene.exe

bin:
  selene: "{{source.asset.bin}}"
